version: '3.9'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lmsabhishek
  api-gateway:
    container_name: api-gateway
    image: abhisheknautiyal/api-gateway:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 9999:9999
    restart: unless-stopped
    depends_on:
      service-registry:
        condition: service_started
  config-service:
    container_name: config-service
    image: abhisheknautiyal/config-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{
     "eureka.client.serviceUrl.defaultZone":"http://service-registry:8761/eureka"
     }'
    ports:
      - 9997:9997
    restart: unless-stopped
    depends_on:
      service-registry:
        condition: service_started
  service-registry:
    container_name: service-registry
    image: abhisheknautiyal/service-registry:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8761:8761
  user-service:
    container_name: user-service
    image: abhisheknautiyal/user-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.cloud.config.uri":"http://api-gateway:9999",
       "eureka.client.serviceUrl.defaultZone":"http://service-registry:8761/eureka",
       "spring.datasource.url":"jdbc:mysql://mysqldb:3306/lmsabhishek?createDatabaseIfNotExist=true",
       "spring.datasource.username":"root",
       "spring.datasource.password":"root"
      }'
    ports:
      - 9996:9996
    restart: unless-stopped
    depends_on:
      service-registry:
        condition: service_started
      mysqldb:
        condition: service_started
  course-service:
    container_name: course-service
    image: abhisheknautiyal/course-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.cloud.config.uri":"http://api-gateway:9999",
       "eureka.client.serviceUrl.defaultZone":"http://service-registry:8761/eureka",
       "loginBaseUrl":"http://api-gateway:9999/api/v/1.0/lms/company/login",
       "spring.datasource.url":"jdbc:mysql://mysqldb:3306/lmsabhishek?createDatabaseIfNotExist=true",
       "spring.datasource.username":"root",
       "spring.datasource.password":"root"
      }'
    ports:
      - 9998:9998
    restart: unless-stopped
    depends_on:
      service-registry:
        condition: service_started
      mysqldb:
        condition: service_started
